site_name: Taller CV — Informe
theme:
  name: material
  language: es
nav:
  - Inicio: index.md
  - Teoría: teoria.md
  - Metodología: metodologia.md
  - Resultados: resultados.md
  - Análisis: analisis.md
  - Bibliografía: bibliografia.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true